### ISSUE TITLE
Too many events are hidden and replaced with ". . ." and cannot be displayed

### ISSUE THREAD

**Issue by LanHikari22** [anufrievroman/minimalist-tui-calendar#50]
This is in day view, depending on the screen height, it hides the events in the day with . . . if there are too many of them. It would be nice to have a keybinding to show these and/or an option to never do . . . and just stretch vertically indefinitely. I also noticed that if the window is too small, it also adds spaces as indicated here:
![image](https://user-images.githubusercontent.com/17696864/229885166-a271a050-1ffe-47e6-8d4d-0cdf8cf3e2b7.png)

**Comment by anufrievroman** [comment]
Hello, thank you for reporting. Yes, it's a bug, I just fixed that in the version 2.8.5, please check if that works for you.
`pip install --upgrade calcure`

**Comment by LanHikari22** [comment]
Hi, thank you for the help and quick response! After upgrading it does seem like the . . . are gone, but now scrolling beyond the screen height causes a fault:

`Traceback (most recent call last):
  File "/home/lan/.local/bin/calcure", line 8, in <module>
    sys.exit(cli())
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 1072, in cli
    curses.wrapper(main)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 1023, in main
    daily_screen_view.render()
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 731, in render
    daily_view.render()
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 417, in render
    user_event_view.render()
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 318, in render
    self.display_line(self.y, self.x, self.info, self.color)
  File "/home/lan/.local/lib/python3.8/site-packages/calcure/__main__.py", line 108, in display_line
    self.stdscr.addstr(y, x, text, curses.color_pair(color.value))
_curses.error: addwstr() returned ERR`

**Comment by LanHikari22** [comment]
Also side note but it calcure reports being version 2.8.2:
![image](https://user-images.githubusercontent.com/17696864/230149210-2a6dd0d1-04ba-4167-a4b0-046e1f026c1a.png)

**Comment by anufrievroman** [comment]
I see, yes, I could reproduce that, but it's quite inconsistent and I couldn't get what's the reason... I'll try to investigate more.

The version might be wrong in -v, the correct one is in on help page `?`

**Comment by anufrievroman** [comment]
Finally, I didn't really understand what's the problem, but I made a fix that prevents the crash, so for me, it works now. However, it seems like your error is a bit different to mine, so please check version 2.8.6

**Comment by LanHikari22** [comment]
Yes, thank you. I can't reproduce the fault anymore so it seems resolved.
